### ISSUE TITLE
Cannot read property 'messageToObject' of undefined

### ISSUE THREAD

**Issue by T1MOXA** [saul/demofile#86] opened 2018-09-23 07:06 UTC
```
C:\Users\T1MOXA\Desktop\demo\node\node_modules\demofile\demo.js:365
        throw e;
        ^

TypeError: Cannot read property 'messageToObject' of undefined
    at DemoFile.demo.on.msg (C:\Users\T1MOXA\Desktop\demo\node\node_modules\demofile\gameevents.js:59:29)
    at DemoFile.emit (events.js:182:13)
    at DemoFile._handleDemoPacket (C:\Users\T1MOXA\Desktop\demo\node\node_modules\demofile\demo.js:229:12)
    at DemoFile._parseRecurse (C:\Users\T1MOXA\Desktop\demo\node\node_modules\demofile\demo.js:328:16)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

Code:
```js
const demofile = require('demofile');
const fs = require('fs');

fs.readFile('test.dem', (err, buffer) => {
    const demoFile = new demofile.DemoFile();

    demoFile.entities.on('create', e => {
        // We're only interested in player entities being created.
        if (e.entity.serverClass.name !== 'CCSPlayer') {
            return;
        }

        console.log('[Time: %d] %s (%s) joined the game', demoFile.currentTime, e.entity.name, e.entity.steamId);
    });

    demoFile.entities.on('beforeremove', e => {
        if (e.entity.serverClass.name !== 'CCSPlayer') {
            return;
        }

        console.log('[Time: %d] %s left the game', demoFile.currentTime, e.entity.name);
    });

    demoFile.parse(buffer);
});

```

**Comment by saul** [comment] 2018-09-23 13:06
Please can you attach the demo in question?

**Comment by T1MOXA** [comment] 2018-09-23 18:31
https://drop.me/op1p4j

**Comment by saul** [comment] 2018-09-24 14:47
So this looks like it's a similar issue to #72 ... I couldn't figure out what the cause was there. If you ran this demo through the official demoinfogo tool, it'd crash as well.

**Comment by T1MOXA** [comment] 2018-09-24 16:34
hm
That's interesting...
OK, I'll keep testing.
Thanks :)

**Comment by T1MOXA** [comment] 2018-09-25 03:50
I checked this demo, it runs normally in cs go.
So the demo working.
Maybe you should write valve ?

**Comment by saul** [comment] 2018-09-26 21:13
OK so I've got a fix for this locally - I'll get around to releasing it soon.

**Comment by T1MOXA** [comment] 2018-10-17 22:49
What about node.js and master branch ?

**Comment by T1MOXA** [comment] 2018-10-17 23:03
How to use this branch ?
I've never used typescript before.
```
npm i https://github.com/saul/demofile.git#typescript
node index
Error: Cannot find module 'demofile'
```

**Comment by saul** [comment] 2018-10-21 09:36
I haven't merged it into master yet. I'll release 1.0.0-beta.1 soon and let you know when you can update.

**Comment by saul** [comment] 2018-10-21 20:03
This has now been released.

**Closed** 2018-10-21 20:04 UTC
Labels: bug, fixed
