### ISSUE TITLE
parsing live demo

### ISSUE THREAD

**Issue by nul0m** [saul/demofile#302] opened 2021-05-15 17:36 UTC
sorry, if that's a duplicate, of some "won't fix" but I didn't manage to find an exact same feature request.. #19 is kind of similar but was just a question as far as I can tell. and there was a bit of extra info here: https://github.com/saul/demofile/discussions/261 

so, how difficult would it be to enable parsing of a growing demo file (e.g. demo of the match being spectated)?

**Comment by saul** [comment] 2021-09-29 11:06
Closing this off as a duplicate of https://github.com/saul/demofile/issues/19. The work to support streaming demos (including demos that are still being written) will be done as part of that issue.

**Closed by saul** 2021-09-29 11:06 UTC
