### ISSUE TITLE
Catch error

### ISSUE THREAD

**Issue by clappis** [saul/demofile#92] opened 2018-11-06 14:41 UTC
if I throw a Error on round_officially_ended event, the class DemoFile catch the exception, but after emit the event "tickent" the app crashs with the exception. if I comment this emit, the next ("end") is emited and i can handle with the error.

This emit "tickend" is util?

**Comment by saul** [comment] 2018-12-09 13:02
Can you give some example code? I don't fully understand what the problem is

**Comment by saul** [comment] 2018-12-11 21:54
Duplicate of #96 - has been fixed. Will release tomorrow

**Closed** 2021-02-28 14:00 UTC
Labels: question
