### ISSUE TITLE
Illegal offset

### ISSUE THREAD

**Issue by CodeAndRun** [saul/demofile#336] opened 2021-12-03 14:10 UTC
Have a bunch of replays not being parsed

```
RangeError: Illegal offset: 0 <= 384129905 (+106) <= 384130000
    at ByteBuffer.module.exports.ByteBufferPrototype.readBytes  (./node_modules/bytebuffer/dist/bytebuffer-node.js:499:23)
    at readIBytes (./node_modules/demofile/dist/demo.js:49:20)
    at DemoFile._handleDemoPacket (./node_modules/demofile/dist/demo.js:217:23)
    at DemoFile._parseRecurse (./node_modules/demofile/dist/demo.js:398:26)
    at processImmediate (node:internal/timers:464:21)
Emitted 'error' event on DemoFile instance at:
    at DemoFile._parseRecurse (./node_modules/demofile/dist/demo.js:437:22)
    at processImmediate (node:internal/timers:464:21)
```

Example replay: https://www.hltv.org/download/demo/66856

Sample code:
```
const fs = require("fs")
const DemoFile = require("demofile").DemoFile

let fnDemo = './runtime/exsto-vs-caught-off-guard-inferno.dem'
fs.readFile(fnDemo, (err, buffer) => {
  const demoFile = new DemoFile()

  demoFile.on("end", e => {
    if (e.error) console.log('Fail', fnDemo, e)
    else console.log('Success', fnDemo)
  })    

  demoFile.parse(buffer)
})
```

**Comment by saul** [comment] 2021-12-15 10:12
Hi. You say "have a bunch of replays not being parsed" - is this just a small portion of the replays you're trying to parse? Or is it replays that were recorded after a certain date/game update? Just trying to figure out if this is down to a small subset of corrupt files or due to a demo format change (unlikely).

In the interim, I suggest ignoring `RangeError` exceptions in the `end` event.

**Comment by TonyaManina** [comment] 2021-12-16 11:35
Seems like it is small part of replays (my current count is ~1/600)
Your guess is these files are corrupted and should be skipped?

**Comment by saul** [comment] 2022-03-22 10:40
Closing this off as 'cannot reproduce' as the demo you linked does parse in full for me.

Let me know if you're still having problems.

**Closed by saul** 2022-03-22 10:40 UTC
Labels: waiting for reporter
