### ISSUE TITLE
RangeError: Illegal length on recent demo

### ISSUE THREAD

**Issue by 1mamute** [saul/demofile#172] opened 2020-10-13 00:35 UTC
Hi, came into this issue while using [csgo-dem2json](https://github.com/n1c/csgo-dem2json) from n1c (it uses demofile too) > https://github.com/n1c/csgo-dem2json/issues/2#issue-718776467

**Describe the bug**
This console output is:
`RangeError: Illegal length: 0 <= 361167691 + 152 <= 361167824`

The demo is farely big (352mb), but i'm not sure this is the issue. 
While i came into this error using dem2json, this also occurs with demofile standalone in a clean enviroment.

**Code to reproduce**
I read a file from a `<input type='file'>` as a buffer, assign some gameEvents then parse it.
The event `demoFile.on("error", (e) => console.log("error: " + e));` returns **error: RangeError: Illegal length: 0 <= 361167691 + 152 <= 361167824**

**Expected behaviour**
Just a normal parsing.

**Affected demos**
The demo Im trying to parse is this: 
[Game 1 - Mirage - Vitality vs FaZe IEM NY 2020](https://www.hltv.org/matches/2344379/vitality-vs-faze-iem-new-york-2020-europe)

>  And have you tried with any others?

I just tried another demo but this time I downloaded directly from the CSGO client and then moved the .dem file from _Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays_ 

After that I tried downloading the exact same demo from HLTV.org
[Game 2 - Inferno - ENCE vs Astralis IEM Katowice 2019](https://www.hltv.org/matches/2331081/ence-vs-astralis-iem-katowice-2019)

Both went nicely. At first I thought HLTV.org did something to the files when uploading the demos, but it worked with this older demo downloading both from Valve servers and HLTV.org. Any chance that new demos have some new protobuf informations that is messing the parser?

**Comment by saul** [comment] 2020-10-13 20:58
Thanks for the report. This is actually a dupe of #11, but I've found a better way to work around it. Fixed in 1.6.0

**Closed** 2020-10-13 20:58 UTC
Labels: bug

**Comment by thecatontheflat** [comment] 2020-10-14 13:26
If I understood correctly, the workaround is to check for the property of the error on demo `end` event?
