### ISSUE TITLE
Self recorded demos rising unexpected error

### ISSUE THREAD

**Issue by Henroks** [saul/demofile#138] opened 2020-02-27 06:00 UTC
**Describe the bug**
Demos recorded by the player (using `record test.dem`) rise error `cannot delete an entity already marked for deletion`. Tested only with Valve's Match Making

**Code to reproduce**
```
let demo = new DemoFile();

demo.parse(demoBuffer); //Demo recorded by the player

demo.on("end", (e) => {
    console.log(e);
});
```

**Stack**
```
AssertionError [ERR_ASSERTION]: cannot delete an entity already marked for deletion
    at Entities._removeEntity (dist\entities.js:323:13)
    at Entities._handlePacketEntities (dist\entities.js:411:26)
    at DemoFile.<anonymous> (dist\entities.js:97:49)
    at DemoFile.emit (events.js:210:5)
    at DemoFile._handleDemoPacket (dist\demo.js:187:14)
    at DemoFile._parseRecurse (dist\demo.js:240:16)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by saul** [comment] 2020-02-27 12:25
Dupe of #72. See an in progress PR here which fixes it: https://github.com/saul/demofile/pull/100

The problem is that supporting in-eye demos results in a significant perf drop. This is because more information needs to be held on to to support them.

**Comment by VitorCaleffi** [comment] 2020-02-27 13:19
Cool. I saw it before, but didn't thought these 2 problems were related. Does demoinfogo also have this problem? Is there a way I could help?

**Comment by saul** [comment] 2020-02-28 08:07
Yes demoinfogo has the same issue - I’ve yet to see a library that does it properly.

**Closed** 2020-02-28 08:08 UTC
Labels: bug
