### ISSUE TITLE
Error: cannot remove non-existent entity

### ISSUE THREAD

**Issue by T1MOXA** [saul/demofile#102] opened 2019-01-12 18:50 UTC
```
Error during parsing: Error: cannot remove non-existent entity
    at Object.assertExists [as default] (\node_modules\ts-assert-exists\lib\index.js:9:15)
    at Entities._removeEntity (\node_modules\demofile\dist\entities.js:316:50)
    at Entities._handlePacketEntities (\node_modules\demofile\dist\entities.js:410:26)
    at DemoFile.demo.on.e (\node_modules\demofile\dist\entities.js:97:49)
    at emitOne (events.js:116:13)
    at DemoFile.emit (events.js:211:7)
    at DemoFile._handleDemoPacket (\node_modules\demofile\dist\demo.js:172:22)
    at DemoFile._parseRecurse (\node_modules\demofile\dist\demo.js:220:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
```

Code:
```js
const demofile = require('demofile');
const fs = require('fs');

fs.readFile('teard.dem', (err, buffer) => {
	const demoFile = new demofile.DemoFile();

   	demoFile.on("end", e => {
	 	if (e.error) {
	   		console.error("Error during parsing:", e.error);
	 	}

	 	console.log("Finished.");
   	});

	demoFile.parse(buffer);
});
```

This error is present in any demo that recorded by player.

**Comment by saul** [comment] 2019-01-13 16:10
Hi @T1MOXA - this is a duplicate of #72. There is a WIP branch on that PR.

**Closed by saul** 2019-01-13 16:10 UTC
Labels: bug, duplicate
